### PR TITLE
Updated README.md for typos fixes and formatting

### PR DESCRIPTION
**Pull request by Ghaniyyat05**

### CODE REVIEW

**Comment by epage** [comment]
This mixes some improvements with some things that are debateable and I'd want to understand why you want to make the change.  If you split this up into individual improvements, we can get some of them merged quickly and then deal with the rest.

**Comment by Ghaniyyat05** [comment]
> This mixes some improvements with some things that are debateable and I'd want to understand why you want to make the change. If you split this up into individual improvements, we can get some of them merged quickly and then deal with the rest.


> Thank you for reviewing my changes! Could you please point out which parts you consider debatable and which are good to add? This will help me split the updates for quicker review.  
> 
> My goal with these changes was to enhance readability. I’m happy to revise further based on your feedback. Looking forward to collaborating!

**Comment by epage** [comment]
As I said, please split this up by change type and we can discuss on those individually.

**Comment by Ghaniyyat05** [comment]
> As I said, please split this up by change type and we can discuss on those individually.

Sure

**Pull request closed without merging**
