### PR TITLE
"substituters", "substituents"

### PR DESCRIPTION
**Pull request by ncfavier**
https://en.wiktionary.org/wiki/substituters
https://en.wiktionary.org/wiki/substituents

Example in the wild: https://nixos.org/manual/nix/unstable/command-ref/conf-file.html#conf-substituters

### CODE REVIEW

**Comment by ncfavier** [comment]
Can't run codegen:

```
$ RUST_BACKTRACE=1 SNAPSHOTS=overwrite cargo test --workspace
    Finished test [unoptimized + debuginfo] target(s) in 0.14s
     Running unittests src/lib.rs (target/debug/deps/codespell_dict-890f24865e68985f)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/codegen.rs (target/debug/deps/codegen-6593a6d441831262)

running 1 test
test codegen ... FAILED

failures:

---- codegen stdout ----
thread 'codegen' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/codespell-dict/tests/codegen.rs:9:54
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /build/rustc-1.65.0-src/library/core/src/result.rs:1107:23
   4: codegen::codegen
             at ./tests/codegen.rs:9:19
   5: codegen::codegen::{{closure}}
             at ./tests/codegen.rs:4:1
   6: core::ops::function::FnOnce::call_once
             at /build/rustc-1.65.0-src/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    codegen

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.27s

error: test failed, to rerun pass `-p codespell-dict --test codegen`
```

**Comment by epage** [comment]
Weird, I can't reproduce that.

You don't need to run the tests for that crate, so you can pass `-p typos-dict` or move into that crates directory and run the tests.

**Comment by ncfavier** [comment]
Getting the exact same error with `crates/typos-dict/tests/codegen.rs:9:54`.

**Comment by ncfavier** [comment]
Ah, I needed rustfmt in PATH.

**Comment by ncfavier** [comment]
ffs

**Pull request merged**
