### PR TITLE
Add "fand" corrections to the dictionary

### PR DESCRIPTION
**Pull request by ianthetechie**
Title says it all :) Accidentally typed "fand" instead of "find" today and there wasn't a rule to catch it.

### CODE REVIEW

**Comment by epage** [comment]
Is there a reason this is pressing?  We collect suggestions for this in a monthly issue and add them all at once, e.g. see #1139.

**Comment by ianthetechie** [comment]
No, not really. sorry I assumed PRs were accepted but upon a re-read of https://github.com/crate-ci/typos/blob/master/CONTRIBUTING.md, I guess I misread and you'd prefer a comment on a monthly updated issue instead?

**Comment by epage** [comment]
They are accepted but they are extra overhead which is not needed in most cases and most people upon finding out about the monthly issue find they would prefer it

**Comment by ianthetechie** [comment]
Understood; will post there next time!

**Pull request merged**
