### PR TITLE
Add `shuould` and `repressented` misspellings

### PR DESCRIPTION
**Pull request by Crown0815**

### CODE REVIEW

**Comment by epage** [comment]
Just wanted to check-in if there was a reason you are needing this now rather than adding it to #897 to be added and released in bulk at the end of the month?

**Comment by epage** [comment]
The intention of #897 is to lower the amount of work for everyone.  One quick update and release is easier on my side and its much easier for users to post the result.

**Comment by Crown0815** [comment]
Understood. 
Since it is not urgent on my side, shall I close this PR and add the typos to #897 then?

**Comment by epage** [comment]
Go ahead and put it there for now.

**Pull request closed without merging**
