### PR TITLE
fix(action) Make wget progress indicator much smaller

### PR DESCRIPTION
**Pull request by szepeviktor**
Because the action runs without a tty, `wget` defaults to `--progress dot`.  This prints a dot per 1K of data.  Due to the size of `typos`, switching to `--progress dot:mega` is better as it only prints one dot per 64K.

```
     0K ........ ........ ........ ........ ........ ........ 51% 11.7M 0s
  3072K ........ ........ ........ ........ ........ .....   100% 12.0M=0.5s
```

### CODE REVIEW

**Comment by epage** [comment]
In the PR, could you contrast it with what it is replacing and explain why this is needed?

From my guess, when the action is run,  `--progress dot` is being used instead of `--progress bar` because it isn't a TTY and the tarball is big enough that a larger increment is needed for printing out a dot.  It is a big help to maintainers to include this kind of context so they can more easily review and merge changes than putting it on them to investigate and guess what is happening.

(honestly, never really noticed the extra dots because I never end up looking at the job output)

**Comment by szepeviktor** [comment]
> never really noticed the extra dots

All I do is under codename "working" is looking at bytes.
Underlying technologies.

**Comment by szepeviktor** [comment]
> explain why this is needed

Excuse me. I handled this repository as my own.
Actually I have a basic rule for bug reports:

1. Where is it happening?
2. Current state
3. Desired state

**Comment by szepeviktor** [comment]
Thank you.
Please squash my commits.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
