### PR TITLE
Typos?

### PR DESCRIPTION
**Pull request by LukasGasp**
contains -> contains
сontain -> contain

Removed those two lines

### CODE REVIEW

**Comment by epage** [comment]
Could you explain why those lines should be removed?

**Comment by szepeviktor** [comment]
> Could you explain why those lines should be removed?

Those two words are the same pairs.

**Comment by szepeviktor** [comment]
@LukasGasp You may have changed line ending.

**Comment by epage** [comment]
Except they aren't the same
```
│001167b0│ 65 2c 7a 6f 6d 62 69 65 ┊ 0a 7a 75 73 65 72 2c 75 │e,zombie┊_zuser,u│
│001167c0│ 73 65 72 0a c3 a9 76 61 ┊ 6c 75 61 74 65 2c 65 76 │ser_××va┊luate,ev│
│001167d0│ 61 6c 75 61 74 65 0a d1 ┊ 81 6f 6e 74 61 69 6e 2c │aluate_×┊×ontain,│
│001167e0│ 63 6f 6e 74 61 69 6e 0a ┊ d1 81 6f 6e 74 61 69 6e │contain_┊××ontain│
│001167f0│ 65 64 2c 63 6f 6e 74 61 ┊ 69 6e 65 64 0a d1 81 6f │ed,conta┊ined_××o│
│00116800│ 6e 74 61 69 6e 65 72 2c ┊ 63 6f 6e 74 61 69 6e 65 │ntainer,┊containe│
│00116810│ 72 0a d1 81 6f 6e 74 61 ┊ 69 6e 65 72 73 2c 63 6f │r_××onta┊iners,co│
│00116820│ 6e 74 61 69 6e 65 72 73 ┊ 0a d1 81 6f 6e 74 61 69 │ntainers┊_××ontai│
│00116830│ 6e 69 6e 67 2c 63 6f 6e ┊ 74 61 69 6e 69 6e 67 0a │ning,con┊taining_│
│00116840│ d1 81 6f 6e 74 61 69 6e ┊ 6f 72 2c 63 6f 6e 74 61 │××ontain┊or,conta│
│00116850│ 69 6e 65 72 0a d1 81 6f ┊ 6e 74 61 69 6e 6f 72 73 │iner_××o┊ntainors│
│00116860│ 2c 63 6f 6e 74 61 69 6e ┊ 65 72 73 0a d1 81 6f 6e │,contain┊ers_××on│
│00116870│ 74 61 69 6e 73 2c 63 6f ┊ 6e 74 61 69 6e 73 0a    │tains,co┊ntains_ │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

**Comment by szepeviktor** [comment]
Are those `c`-s Russian s-es??

**Comment by epage** [comment]
Unsure which unicode character they are but someone felt the need to contribute that set.

**Pull request closed without merging**
